version: "3.0"

services:
  app:
    container_name: linden-honey-app
    build: .
    ports:
     - "8080:8080"
    networks:
      - linden-honey-net
    links:
     - db
    environment:
     - APP_HOST=app
     - APP_PORT=8080
     - DB_URL=mongo://db:27017/linden_honey_local
  db:
    container_name: linden-honey-mongodb
    image: "mongo:latest"
    expose:
     - "27017"
    networks:
      - linden-honey-net

networks:
  linden-honey-net:
    driver: bridge
