version: "3.7"

services:
  db:
    container_name: core_db
    image: bitnami/mongodb:4.2.2
    environment:
      MONGODB_USERNAME: linden-honey
      MONGODB_PASSWORD: linden-honey
      MONGODB_DATABASE: linden-honey
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - internal
    volumes:
      - db_data:/bitnami

  app:
    container_name: app
    image: lindenhoney/linden-honey:latest
    build: .
    depends_on:
      - db
    environment:
      APPLICATION_DB_URI: mongodb://linden-honey:linden-honey@core_db:27017/linden-honey
    ports:
      - 80:8080
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge
