version: "3.0"

services:
  db:
    container_name: linden-honey-db
    image: "mongo:latest"
    ports:
     - "27017:27017"
    networks:
      - linden-honey-net
  app:
    container_name: linden-honey-app
    build: .
    ports:
     - "8080:8080"
    networks:
      - linden-honey-net
    links:
     - db
    environment:
     - APP_HOST=app
     - APP_PORT=8080
     - DB_URL=mongodb://db:27017/linden_honey_local

networks:
  linden-honey-net:
    driver: bridge
