version: "3"

services:
  db:
    container_name: linden-honey-db
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_USERNAME=linden-honey
      - MONGODB_PASSWORD=linden-honey
      - MONGODB_DATABASE=linden-honey
    ports:
      - 27017:27017
    volumes:
      - linden-honey-db-data:/bitnami
    networks:
      - linden-honey-net
  app:
    container_name: linden-honey-app
    build: .
    environment:
     - LH_SERVER_PORT=8080
     - LH_DB_URI=mongodb://linden-honey:linden-honey@db:27017/linden-honey
    ports:
     - "8080:8080"
    networks:
      - linden-honey-net
    links:
     - db

volumes:
  linden-honey-db-data:

networks:
  linden-honey-net:
    driver: bridge
